export:
  seeddistro: Ubuntu-24.04
  exportpath: C:\Ubuntu
import:
  installlocation: C:\Ubuntu\Installs
distros:
  #UK Pod
  - sdpay
  - smpay
  - mhpay
  - gvpay

  #India Pod
  - vkpay
  - vikpay
  - mppay
  - rjpay
  - rmpay

  #US Pod
  - cwpay
  - cypay
  - hvpay
  
sudousers:
    #UK Pod
  - sdpay
  - smpay

  #India Pod
  - vkpay
  - vikpay
  - mppay
  - rjpay
  - rmpay